version: '3'

services:
    backend_api:
        build: .
        command: python manage.py runserver 0.0.0.0:8000
        # Todo: I'' not setting the custom settings file because I'' need change the cache approach to local memcache
        # and today we have database table approach.
#        command: ["python", "manage.py", "runserver", "0.0.0.0:8000",
#                            "--settings=spotify.settings.hom" ]
        container_name: server
        volumes:
            - .:/code
        ports:
            - "8000:8000"

    db_postgres:
        image: postgres
        container_name: postgres_db
        environment:
            POSTGRES_USER: postgres
            POSTGRES_DB: postgres
            POSTGRES_PASSWORD: postgres
        volumes:
            - db_data:/var/lib/postgresql/data/

volumes:
    db_data: